config/routes.rb
Rails.application.routes.draw do
  get 'pages', to: 'pages#one'
  get 'two', to: 'pages#two'
  get 'three', to: 'pages#three'
  root 'pages#one'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS 4.6.0 VERSION-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Challenge</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"     data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"    aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon text-light"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <%= link_to('Page One', pages_path, class: 'nav-link') %>
            <%= link_to('Page Two', two_path, class: 'nav-link') %>
            <%= link_to('Page Three', three_path, class: 'nav-link') %>
        </div>
      </div>
    </nav>

    <%= yield %>

    <!--Jquery 3.5.1 Version-->
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>

    <!-- jQuery and Bootstrap(4.6.0 Version) Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/one.html.erb
<div class="info container">
<h1>Shirley A.</h1>
</div>

app/views/pages/three.html.erb
<div class="info container">
<h2>Page Three </h2>
<p>El trozo de texto estándar de Lorem Ipsum usado desde el año 1500 es reproducido
 debajo para aquellos interesados. Las secciones 1.10.32 y 1.10.33 de "de Finibus 
 Bonorum et Malorum" por Cicero son también reproducidas en su forma original exacta, acompañadas por versiones en Inglés de la traducción realizada en 1914 por H. Rackham.</p>
 </div>

app/views/pages/two.html.erb
<div class="info container">
<h1>Page Two</h1>
<img src="<%= asset_path "capture_rails_routs.png" %>" width= 100%/>
</div>